#!/bin/sh

JAVA_OPTS="-server \
    -Dfile.encoding=UTF-8"

if [ -n "$HEAP_SIZE" ];  then
    JAVA_OPTS="$JAVA_OPTS -Xms$HEAP_SIZE -Xmx$HEAP_SIZE"
else
    JAVA_OPTS="$JAVA_OPTS -Xms512m -Xmx512m"
fi

if [ -n "$PROFILE" ];  then
    JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=$PROFILE"
else
    JAVA_OPTS="$JAVA_OPTS -Dspring.profiles.active=prod"
fi


java $JAVA_OPTS -jar /opt/springboot-angular-seed.jar